#!/bin/bash

echo "🚀 Phase 6.5 Migration - Supabase SQL 실행 가이드"
echo ""
echo "====================================================="
echo " 이 마이그레이션은 Supabase Dashboard에서 실행해야 합니다"
echo "====================================================="
echo ""
echo "📋 실행 단계:"
echo ""
echo "1. Supabase Dashboard 열기"
echo "   → https://supabase.com/dashboard"
echo ""
echo "2. 프로젝트 선택 후 'SQL Editor' 메뉴로 이동"
echo ""
echo "3. 아래 파일의 내용을 복사하여 붙여넣기:"
echo "   → phase65-migration-combined.sql"
echo ""
echo "4. 'Run' 버튼 클릭"
echo ""
echo "====================================================="
echo ""
echo "📄 마이그레이션 파일 내용 미리보기:"
echo ""
cat phase65-migration-combined.sql
echo ""
echo "====================================================="
echo ""
echo "✅ 실행 후 확인사항:"
echo ""
echo "  1. Table Editor → bookings 테이블"
echo "     - payment_method 컬럼 있는지 확인"
echo "     - user_id 컬럼 있는지 확인"
echo "     - payment_status 컬럼 있는지 확인"
echo "     - cancelled_at 컬럼 있는지 확인"
echo ""
echo "  2. Database → Functions"
echo "     - create_booking_with_prepaid 함수 있는지 확인"
echo "     - cancel_booking_restore_prepaid 함수 있는지 확인"
echo ""
echo "====================================================="
